import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@unocss/reset/tailwind.css';
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contract Wise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <div className="flex h-screen">
            <QueryProvider>
              <Sidebar />
              <main className="flex-1 overflow-auto">
                {children}
              </main>
              <Toaster position="top-center" />
            </QueryProvider>
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
